### ISSUE TITLE
Space Menu issues

### ISSUE THREAD

**Issue by Felli** [sashatravkina/humhub1.3.6-themes-flathub#1]
Hello, I'm glad to see this theme back on the market, sadly I'm seeing one issue on my end.
![screenshot_1](https://user-images.githubusercontent.com/2011633/47273620-8e2d9300-d5d2-11e8-8640-f2b061f31bea.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.6 |
| PHP version      | 7.2 |
| Operating system | LinuxOS |

**Comment by kodersha** [comment]
Hello. When does this bug appear?

**Comment by Felli** [comment]
As soon as I enable the theme.

**Comment by kodersha** [comment]
Strange. I can not cause this bug on my HumHub. What plugins are installed? Can you take a screenshot of the source code of this item in your browser?

**Comment by Felli** [comment]
Got the issue down, it would seem if users have spacetypes enabled via EE modules then this will happen to the theme. :wink:

**Comment by Felli** [comment]
Within the spacetype module (Inside of the EE module) the tags for `<li></li>` are used as well as the default `spaceChooser.php` but within your theme `<div></div>` are used so this happens if a user is using the EE module. The best solution would be for HumHub to adopt this method @luke- and it would be for cleaner coding, but I'll leave that up to the core team to decide on.

**Comment by kodersha** [comment]
Tell me, where is EE module? How can I turn them on?

**Comment by Felli** [comment]
The EE module is short for the enterprise edition of HumHub, which is a module basically and can't be edited by outside sources other than those that install it via the marketplace and the core team.

**Comment by kodersha** [comment]
Then I have no opportunity to fix this error. 🤔

**Comment by Felli** [comment]
I would appreciate it if this could stay open till Luke can see this and make a decision if we should adopt the use of `<div></div>` in both `spaceChooser.php`, I've already got the fix for the `spacetype` issue. :+1:

**Comment by Felli** [comment]
Should be fixed now.
![screenshot_8](https://user-images.githubusercontent.com/2011633/48679565-49971680-ebd5-11e8-9018-094975ffab5f.png)
